[package]
name = "gdcf"
version = "0.1.0"
edition = "2018"
include = ["../README.md"]

[dependencies]
futures = "^0.1.17"
chrono = "^0.4.0"
log = "^0.4.0"
failure = "0.1.2"
failure_derive = "0.1.2"
derive_more = "*"

[dependencies.gdcf_model]
path = "../gdcf_model"